naver/egjs-flicking

src/flicking.js, test/unit/resize.spec.js
Removed '_checkPadding()'. It doesn't necessarily need to check the difference and applying padding of panels, because call of resize is up to the decision of user.
Ref https://github.com/naver/egjs/issues/489
=> fix(flicking): Fix on previewPadding resizing

src/Flicking.js, test/unit/resize.spec.js
Set condition to check if panel is animating
Ref #https://github.com/naver/egjs/issues/492
=> fix(resize): Prevent resize executed during panel animation

src/Flicking.js, test/unit/restore.spec.js
#23 
Fix to not be called restore event in normal flow, after restoration happening
=> fix(Flicking): Correct wrong restore event calls

src/flicking.d.ts
There is a problem i TS compilation because `Flicking` did not inherit the parent class `Component`.
=> chore(flicking.d.ts): Update to extends Component

src/Flicking.js, test/unit/resize.spec.js
#77
There's no reason update container's width value as total panel's width.
It keeps to be 100% width to prevent styling issue.
=> fix(resize): Remove updating container's width

src/Flicking.js, src/config.js, test/unit/options.spec.js
#83
New option for setting z-index value for container element, which was fixed to 2000 before.
=> feat(options): Intent to ship zIndex option

src/plugin/Plugin.js, src/plugin/effects/OpacityEffect.js, src/plugin/effects/ParallaxEffect.js
#103
Correct mal-functioning when move APIs(.next()/.prev()) called
=> fix(plugin): Correct for API moves

src/Flicking.ts, src/components/Panel.ts, src/components/PanelManager.ts, src/components/Viewport.ts, src/states/AnimatingState.ts, src/states/DraggingState.ts, src/states/HoldingState.ts, src/states/IdleState.ts, src/states/State.ts, src/utils.ts, test/manual/test.js, test/unit/Panel.spec.ts, test/unit/PanelManager.spec.ts, test/unit/assets/utils.ts, test/unit/initialize.spec.ts, test/unit/methods.spec.ts
Fixes #171 
It also resolves #174 
- This changes internal interface from FlickingPanel to real Panel's instance
- #171 is now fixed.
- #174 is also handled on this PR.
=> fix: recalculate target panel when interrupted

src/Flicking.ts, src/components/Panel.ts, src/components/Viewport.ts, src/consts.ts, src/moves/FreeScroll.ts, src/moves/MoveType.ts, src/moves/Snap.ts, src/states/AnimatingState.ts, src/states/DraggingState.ts, src/types.ts, src/utils.ts
#189, #190, #191 
- This fixes #190  
- It also fixes #191 
- This is an pre-work for #189
=> refactor: make classes for each move types

src/components/Viewport.ts, src/states/DisabledState.ts, test/manual/test.js, test/unit/Panel.spec.ts, test/unit/PanelManager.spec.ts, test/unit/events.spec.ts, test/unit/methods.spec.ts
#184, #185
- This fixes #184 
- This also fixes #185
=> fix: calling stop() to stop event immediately

src/states/AnimatingState.ts
=> fix: interrupting at bounce area

demo/features/infiniteflicking.html, packages/react-flicking/src/demo/features/InfiniteFlicking.tsx, packages/react-flicking/src/react-flicking/Flicking.tsx, packages/vue-flicking/demo/features/Infinite.vue, packages/vue-flicking/package-lock.json, packages/vue-flicking/package.json, packages/vue-flicking/src/Flicking.ts, packages/vue-flicking/src/utils.ts, src/Flicking.ts, src/components/Panel.ts, src/components/PanelManager.ts, src/components/Viewport.ts, src/consts.ts, src/types.ts, test/unit/events.spec.ts, test/unit/methods.spec.ts
#273
This PR is made to match the rendering method same with native's.
That is, when a new panel threw in, the framework should render new panels with visible ones to calculate size.
This also implements `isEqualSize` and `isConstantSize` options for framework Flickings.
The real implementation is only available for only Vue-Flicking yet.
=> fix: match framework rendering with native rendering

src/states/HoldingState.ts
#303 
- "select" event is always triggered on mobile devices regardless of touch position at "touchend" event
This resolves #303
=> fix: "select" event on mobile device

src/components/Viewport.ts, test/manual/html/resize.html, test/unit/assets/fixture.ts, test/unit/options.spec.ts
#333, #334
Height resizing with adaptive option does not work after #318.
I've fixed that bug & added some test codes for the adaptive option.
=> fix: adaptive options not works after #334

packages/react-flicking/README.md, packages/react-flicking/src/react-flicking/Flicking.tsx, packages/react-flicking/src/react-flicking/consts.ts, packages/react-flicking/src/react-flicking/types.ts, packages/vue-flicking/README.md, packages/vue-flicking/src/Flicking.ts
#339 
This adds 2 following new props to the Flicking component of React & Vue.
- viewportTag: set the tag name of the viewport element(`eg-flick-viewport`)
- cameraTag: set the tag name of the camera element(`eg-flick-camera`)
This closes #339
=> feat: add viewportTag and cameraTag to frameworks

package-lock.json, src/components/Viewport.ts, test/manual/html/default.html, test/manual/js/default.js, test/unit/assets/fixture.css, test/unit/assets/fixture.ts, test/unit/methods.spec.ts, test/unit/options.spec.ts
#376
This fixes #376
This also adds test cases for when all panels have 0 widths.
=> fix: wrong camera position after resizing

src/Flicking.ts, test/unit/methods.spec.ts
#389
This fixes the additional issue of #389 that adding `circular: true` option can reproduce the issue.
=> fix: wrong rendering indexes with renderOnlyVisible: true & circular: true

src/Flicking.ts, src/consts.ts, test/unit/methods.spec.ts
#401 
This adds a new method for Flicking, `getSize()` which returns the size of the viewport
=> feat: add getSize

src/Flicking.ts, src/components/PanelManager.ts, test/manual/html/resize.html, test/manual/js/resize.js, test/unit/methods.spec.ts
This fixes issue that resize throws an error when there're empty panels between solid panels.
=> fix: resize throws error when there're empty panels

.eslintrc.js, src/Flicking.ts, src/cfc/withFlickingMethods.ts
#458 
This adds the following missing methods to framework Flickings
- resize
- on, once, trigger, off
=> fix: missing resize in withFlickingMethods

src/core/panel/Panel.ts, test/unit/core/Panel.spec.ts
=> fix: select event can throw error when there's no element on panel in frameworks

src/index.umd.ts
=> fix: umd not exports cfc methods

src/control/AxesController.ts
This restores missing `releaseOnScroll` option for Axes that was previously used in Flicking v3
=> fix: set axes releaseOnScroll to true

src/Flicking.ts, src/utils.ts, test/unit/methods.spec.ts
This fixes case that flicking doesn't update `currentPanel` after calling `sync`
=> fix: set new currentPanel when current is removed

packages/svelte-flicking/src/flicking.svelte
This fixes issue that plugins are not updated on svelte after initialization
=> fix: plugins are not updated on Svelte

src/camera/BoundCamera.ts, test/manual/js/index.js, test/unit/camera/BoundCamera.spec.ts
#505 
This fixes #505 
"prev"
"next"
"center"
"20%"
=> fix: bound not working when there're not enough panels to fill the viewport

docs/src/demo/code/LazyLoad/js.tsx, docs/src/pages/Demos.mdx
This will remove the pre-deployed lazyload demo, as it's not properly prepared yet.
That demo can have memory issues with old devices, so I'll remove that demo for now, and will add it again when it's prepared.
=> docs: rollback lazyload demo

packages/svelte-flicking/src/Flicking.js
=> fix: svelte ssr constructor not found

src/cfc/withFlickingMethods.ts
=> fix: getter is called initialization on vite

docs/docs/quick-start.mdx
Closes https://github.com/naver/egjs-flicking/issues/639
`class` is not used in React(JSX)
This resolves #639
=> docs: Fix class to className in example

docs/src/demo/DateSelector.tsx, packages/react-flicking/package.json, packages/react-flicking/src/demo/App.tsx, packages/react-flicking/src/demo/features/FreeScroll.tsx, packages/react-flicking/src/index.tsx, packages/react-flicking/src/react-flicking/Flicking.tsx, packages/react-flicking/src/react-flicking/ReactRenderer.ts, packages/react-flicking/tsconfig.json, packages/react-flicking/tsconfig.paths.json, src/Flicking.ts, src/camera/Camera.ts, src/renderer/Renderer.ts, test/manual/index.html, test/manual/js/index.js, test/unit/Flicking.spec.ts, test/unit/camera/Camera.spec.ts, test/unit/core/panel/Panel.spec.ts
#643 
This fixes #643 & Flickering behavior in React 18 by changing most of the `init()`'s code to be synchronous.
=> fix: broken rendering on React 18

src/cfc/sync.ts, src/renderer/Renderer.ts
This fixes the broken `sync` implementation when an entry of `ordered` is included in the diff result.
=> fix: wrong sync if ordered is included

docs/src/css/custom.css, docs/src/demo/Nested.tsx, docs/src/pages/Demos.mdx, docs/src/pages/Options.mdx, package-lock.json, package.json, src/Flicking.ts, src/control/AxesController.ts, test/cfc/common/jest.config.js, test/cfc/common/simulate.ts, test/manual/js/nested.js, test/manual/nested.html, test/unit/Flicking.spec.ts
`nested` is added to `FlickingOptions` and you can define the movement of Flicking inside Flicking.
If `nested` is set to true, the parent Flicking will start moving if the child Flicking reaches the start/end of the panels.
If `nested` is set to false, parent Flicking does not move when user swipes child Flicking.
Also added examples of nested option applied to Options page and Demos page of documentation.
=> feat: add nested option

README.md
The deepscan badge is rounded but others are flat, so I view the docs and find a solution.
Just make the badges have the same style, link  here: https://flat.badgen.net/#deepscan
Before:
After:
=> docs: update deepscan badge for unified style

package-lock.json, package.json
#673 
It uses the 3.2.0 version of the Axes and sets appropriate touch-action according to the drag direction of Flicking.
For horizontal flicking, touch-action is set to pan-y. And for vertical flicking, touch-action is set to pan-x.
=> fix: use appropriate touch-action for element

package-lock.json, package.json
#677 
Updated Axes to 3.2.1.
Fixes made in Axes 3.2.1 can make Flicking work properly in IOS Safari browser.
=> fix: Flicking not working in iOS Safari browser

package-lock.json, package.json
#677 
Fixed an error where drag gestures still didn't work on iOS, updating Axes to 3.2.2
[This is pre-release demo that resolved the problem that occurred in iOS.](https://malangfox.github.io/egjs-flicking/Demos)
=> fix: unable to drag, swipe in iOS Safari

src/control/AxesController.ts, test/unit/Flicking.spec.ts
Fixed the issue that next click did not work when moving the Flicking using `moveTo` after `disableInput`.
`disableInput` disables PanInput, so setting `dragged` to `false` when `hold` is made in `PanInput` no longer occurs.
If coordinate change is made in Axes using `moveTo` while `PanInput` is disabled, `dragged` becomes `true`, but `hold` does not occur in PanInput at the next click.
[Example of onClick not working after using moveTo by button while input is disabled.](https://codepen.io/malangfox/pen/zYRawpb) To check this error, click a Panel once, and click Next button, and click a Panel.
Since `PanInput` is used in Flicking for dragging gesture, we should set `dragged` to `true` only when `PanInput` is enabled.
=> fix: prevent click works even when input is disabled

packages/react-flicking/src/react-flicking/ViewportSlot.tsx
Sometimes ViewportSlot has only one children such as Plugin Pagination. 
So I think ViewportSlot children type must be React.ReactElement[] or React.ReactElement.
=> refactor: add union type to ViewportSlot

package-lock.json, package.json, src/Flicking.ts, test/unit/Flicking.spec.ts
#702 
When the width of each panel is less than 33% of the viewport, using the SnapControl and `bound` options together will cause an error.
We use [`findActiveAnchor`](https://github.com/naver/egjs-flicking/blob/master/src/camera/Camera.ts#L394-L399) in `moveToPosition` of SnapControl.
However ` find(this._anchors, anchor => anchor.panel.index === activeIndex)` can return `null` depending on the panel index of the anchors. This throws `POSITION_NOT_REACHABLE` error that makes SnapControl not working.
By default, [Flicking's `defaultIndex` is 0.](https://github.com/naver/egjs-flicking/blob/master/src/Flicking.ts#L799)  Also Flicking [sets the initial panel](https://github.com/naver/egjs-flicking/blob/master/src/Flicking.ts#L1505) to this 0th panel.
When the width of each panel is less …
=> fix: bound option causing error when using with specific panel width

package.json, src/Flicking.ts, src/control/AxesController.ts, src/control/Control.ts, src/control/states/HoldingState.ts, test/unit/Flicking.spec.ts, test/unit/control/Control.spec.ts
#709 
If `onChange` occurs while Flicking is in the holding state, we check the `offsetX` or `offsetY` of the native event that caused the change.
```ts
const inputEvent = axesEvent.inputEvent as { offsetX: number; offsetY: number };
const offset = flicking.horizontal
? inputEvent.offsetX
: inputEvent.offsetY;
```
However, there is no native event when we try to move the holding state Flicking using the method like `moveTo`. This will cause an error `Cannot read properties of null (reading 'offsetX')`.
[You can check the error in this demo.](https://codepen.io/malangfox/pen/NWYvQKW)
This changes `onChange` to check the direction using `animatingContext` instead of the native event when Flicking moves in a way other than a native event.
=> fix: fix error when onChange occur during holding state

packages/react-flicking/src/react-flicking/Flicking.tsx
#716 
This fixes the error that the event handler registered in react-flicking does not applies the updated state.
If we use the state declared be `useState` inside the event handler, the most recently updated state is not reflected correctly.
[In this demo, you can compare the results when adding a log by pressing a button and executing the same function as an event handler by moving Flicking.](https://codesandbox.io/s/egjs-flicking-v4-on-move-end-891kwx)
If this same function `holdStart` is executed as an event handler for Flicking, logs are recognized as an empty array in its initial state and the array will become empty.
This has been fixed by using event handlers with the correct scope.
=> fix: fix updated state not applied in event handler functions in React

packages/ngx-flicking/projects/ngx-flicking/src/lib/ngx-flicking.component.ts, packages/preact-flicking/README.md, packages/react-flicking/README.md, packages/react-flicking/src/react-flicking/Flicking.tsx, packages/react-flicking/src/react-flicking/consts.ts, packages/react-flicking/src/react-flicking/types.ts, packages/svelte-flicking/src/Flicking.d.ts, packages/svelte-flicking/src/flicking.svelte, packages/vue-flicking/README.md, packages/vue-flicking/src/Flicking.ts, packages/vue-flicking/src/FlickingProps.ts, packages/vue3-flicking/README.md, packages/vue3-flicking/src/Flicking.ts, packages/vue3-flicking/src/FlickingProps.ts, packages/vue3-flicking/src/types.ts
This change allows adding additional classes to `flicking-camera` element.
```html
<Flicking cameraClass="myclass1 myclass2">
<div className="panel"></div>
<div className="panel"></div>
<div className="panel"></div>
</Flicking>
```
```html
<flicking :cameraClass="'myclass1 myclass2'">
<div class="panel"></div>
<div class="panel"></div>
<div class="panel"></div>
</flicking>
```
```html
<ngx-flicking [cameraClass]="'myclass1 myclass2'">
<div flicking-panel class="panel"></div>
<div flicking-panel class="panel"></div>
<div flicking-panel class="panel"></div>
</ngx-flicking>
```
```html
<Flicking cameraClass={"myclass1 myclass2"}>
<FlickingPanel><div class="panel"></div></FlickingPanel>
<FlickingPanel><div class="panel"></div></FlickingPanel>
<FlickingPanel><div …
```
=> feat: add cameraClasses property

package.json, packages/preact-flicking/package.json, packages/react-flicking/package.json, packages/svelte-flicking/package.json, packages/vue-flicking/package.json, packages/vue3-flicking/package.json
fixes https://github.com/naver/egjs-flicking/issues/708, https://github.com/naver/egjs-flicking/issues/573
이슈는 nuxt + production 환경일 때 flicking.css파일이 사라진다는 내용입니다.
제 개발 환경이 react + 자체 ssr + production 환경임에도 해당 현상이 재현되어 공통점을 찾아보았습니다.
webpack@4
production 환경에서만 MiniCssExtractPlugin(webpack@4 호환 1.6.2), OptimizeCSSAssetsPlugin이 적용되어있습니다. 이 경우 재현이 가능한것으로 보입니다.
develop 환경에서는 style-loader를 사용하고 있습니다.
eg-js/flicking은 v4로 버전업 되면서 dist의 css 파일을 import해 사용하는 방식으로 변경되었습니다.
그러나 package.json의 sideEffects가 css파일을 별도로 제공하지 않을때 기준 그대로 false로 적용되어있습니다.
이 부분을 변경해주면 Flicking.css가 MiniCssExtractPlugin 1.6.2에서도 사라지지 않는것을 확인할 수 있습니다.
임시 해결방법으로는 아래 내용을 이용할 수 있습니다.
[Webpack - Mark the file as side-effect-free](https://webpack.kr/guides/tree-shaking/#mark-the-file-as-side-effect-free)
```
마지막으로 "sideEffects"는 …
```
=> fix: add css files to sideEffects field of all packages

docs/docs/tutorials/quick-start.mdx, packages/react-flicking/README.md, packages/react-flicking/src/react-flicking/Flicking.tsx, packages/react-flicking/src/react-flicking/consts.ts, packages/react-flicking/src/react-flicking/types.ts
This adds a new prop `renderOnSameKey` for react-flicking, which can disable Flicking's behavior which it doesn't render when the prop `children` has the same length & keys.
=> feat: add renderOnSamekey for react-flicking

src/control/AxesController.ts, test/unit/Flicking.spec.ts
According to [document](https://naver.github.io/egjs-flicking/Options#preventclickondrag), `preventClickOnDrag` option prevent `click` event if the user has dragged at least a single pixel on the viewport element.
However, some `pointermove` events have both the `movementX` and `movementY` properties of 0 and have a coordinate change less than 1 pixel.
<details>
<summary>see example `pointermove` event</summary>
```
isTrusted: true
altKey: false
altitudeAngle: 1.5707963267948966
azimuthAngle: 0
bubbles: true
button: -1
buttons: 1
cancelBubble: false
cancelable: true
clientX: 534.2734375
clientY: 60.5078125
composed: true
ctrlKey: false
currentTarget: null
defaultPrevented: true
detail: 0
eventPhase: 0
fromElement: null
height: 1
isPrimary: true
layerX: 534
layerY: 60
metaKey: false …
```
=> fix: fix preventClickOnDrag option working for less than 1px

docs/package.json, docs/src/css/custom.css, docs/src/pages/Plugins.mdx
This updates documentation for [animationDuration](https://github.com/naver/egjs-flicking-plugins/pull/45) and [delayAfterHover](https://github.com/naver/egjs-flicking-plugins/pull/46) options for AutoPlay plugin.
=> docs: update AutoPlay plugin docs

src/Flicking.ts
#762 
Update Link to the option was added to the property section of the api document. 
Fixed non-working links with new ones.
Is there a better way to link?
I would be grateful if you could let me know if there is.
=> docs(NavigationToOptions): Update API document

src/core/ResizeWatcher.ts
Fix misspelled event name "resize" on removeEventListener
=> fix: misspelled event name on removeEventListener

src/control/SnapControl.ts, src/control/StrictControl.ts, test/unit/control/SnapControl.spec.ts, test/unit/control/StrictControl.spec.ts
#776
When control is set to SnapControl or StrictControl, click event during panel sliding triggers restore behavior.
``` js
// src/control/SnapControl.ts > SnapControl > moveToPosition
// Restore to active panel
return this.moveToPanel(activeAnchor.panel, {
duration,
axesEvent
});
```
To reproduce, go to [official demo](https://naver.github.io/egjs-flicking/ko/Demos), drag fast, then click during sliding. When mouseup, the panel restores to starting position.
However this behavior in most circumstances are rather confusing to end user since the camera has already moved far from original panel but it restores to original position.
So it would feel more natural for camera to slide to nearest panel when interrupted.
``` js
// src/control/SnapControl.ts > SnapControl > moveToPosition
// …
```
=> fix: control fallback when interrupted

docs/docusaurus.config.js, src/control/AxesController.ts, src/utils.ts, test/unit/control/AxesController.spec.ts
When using a specific combination of options such as below, the internal position exceeds the range of coordinates.
```
{
circular: true,
align: "prev",
duration: 0,
moveType: "strict"
}
```
Here is the [reproduction demo](https://codepen.io/malangfox/pen/QWByPgp) of this issue.
When you click the panel, the internal coordinates and range change as shown below at the last point,
And when you interact with Flicking once more, it shows an abnormal movement to return this value to 0 in the range.
This was because the `animateTo` in AxesController updates the range and position one more time separately from the strict control update range and position when duration is 0.
According to what I have checked, only the strict type has the behavior of changing the pos and range of the Axes instance …
=> fix: prevent invalid coordinate value in AxesController

packages/ngx-flicking/projects/ngx-flicking/src/lib/NgxRenderer.ts, packages/react-flicking/src/react-flicking/ReactRenderer.ts, packages/svelte-flicking/src/SvelteRenderer.ts, packages/vue-flicking/src/VueRenderer.ts, packages/vue3-flicking/src/VueRenderer.ts, src/Flicking.ts, src/camera/Camera.ts, src/renderer/Renderer.ts, src/renderer/VanillaRenderer.ts, test/manual/js/index.js
#773 
This fixes #773 by delaying CSS transform application until the elements are fully rendered in the correct order.
This can fix panels flickering on the first render in the SSR frameworks.
=> fix: apply transform after elements are fully rendered

packages/react-flicking/src/index.tsx, packages/react-flicking/src/react-flicking/ReactRenderer.ts, src/renderer/Renderer.ts
This fix resolves #785 
This issue seems to be happening in strict mode in react, and I am considering whether we should provide this fix for every framework environment for the possibility of a similar issue may be happening.
If so, I'll fix the vue and svelte parts too.
=> fix: off render event handling when destroy occurs

docs/docs/tutorials/quick-start.mdx
#793 
This fixes misspelled css path in quick start document.
=> docs: fix misspelled path in document

src/Flicking.ts
#795 
A [demo](https://codepen.io/malangfox/pen/QWVebpj) that reproduces the issue.
This is a bug caused by `if (index)` is false when index is 0.
=> fix: fix setStatus not working when index is 0

docs/docs/tutorials/listening-to-events.mdx
Ref #798
798
- before
```
You can listen to Flicking's events with [Flicking#on](api/Flicking#on)
```
- after
```
You can listen to Flicking's events with [Flicking#on](useBaseUrl(api/Flicking#on))
```
=> docs(egjs-flicking): tutorial doc contains link that 404s

docs/i18n/ko/docusaurus-plugin-content-docs/current/api/Flicking.mdx, docs/i18n/ko/docusaurus-plugin-content-docs/version-4.10.7/api/Flicking.mdx, docs/src/pages/Demos.mdx, docs/versioned_docs/version-4.10.7/api/Flicking.mdx, docs/versioned_sidebars/version-4.10.7-sidebars.json
#791 
https://malangfox.github.io/egjs-flicking/Demos#variable-size-panels
This adds a link to the circular option in the first circular Demo area of the documentation.
When checking the implementation demo of the `circular` option, it is recommended that users note the warning statement related to the size of the Panel.
In addition, this adds the missing documentation pages found in #798.
=> docs: add info for circular option in related demo

README.md, package-lock.json, packages/ngx-flicking/README.md, packages/ngx-flicking/projects/ngx-flicking/README.md, packages/preact-flicking/README.md
There are two `Documentation` links in the README.md, the one at the bottom is outdated.  
I found the old links in the README.md of the root, ngx, and preact packages and fixed them with the newer links that were changed in 4.x.
=> docs: update documentation link to newest at bottom of README.md

packages/ngx-flicking/projects/demo/src/app/app.module.ts, packages/ngx-flicking/projects/ngx-flicking/src/lib/ngx-flicking.component.ts
=> fix: add missing styleUrls in ngx-flicking

package-lock.json, package.json, src/Flicking.ts, src/camera/Camera.ts, src/const/external.ts, src/control/AxesController.ts, test/manual/css/index.css, test/manual/js/rtl.js, test/manual/rtl.html, test/unit/Flicking.spec.ts, test/unit/camera/Camera.spec.ts, test/unit/helper/El.ts
#835 
This issue fixes the layout breaking when `direction: rtl` is applied to the viewport.
=> fix: fix broken layout when direction rtl is applied

src/control/Control.ts, src/control/StrictControl.ts, test/unit/control/StrictControl.spec.ts
#841 
When using the next Panel to move in `moveType: strict`, we use the following rules
1. find the `anchorAtPosition` that is closest to the point the camera is currently showing.
2. if `anchorAtPosition` is not the same as Flicking's current Panel, we move to anchorAtPosition.
3. if `anchorAtPosition` is the same as Flicking's current Panel, navigate to `adjacentAnchor` which is the next/prev anchor of `anchorAtPosition`.
However, there is an exception to this rule that can cause an error when you rotate the circular Flicking once before the event that updates the current panel is fired,  
If you rotate the Flicking once, you'll end up in a situation where the camera is showing the position of the current panel again.
If that happens, you won't be able to stop on that panel by step 3 …
=> fix: strict movetype moving wrong panel on circular flicking

src/control/Control.ts, test/unit/Flicking.spec.ts
#854 
This fixes the behavior of `getDirection`, fixing cases where the direction of the `willChange` event is incorrect.
=> fix: fix direction of willChange event when circular

src/camera/Camera.ts, test/unit/control/SnapControl.spec.ts
#850
https://codepen.io/malangfox/pen/WNmPemg
Pressing the moveTo button, opening the console, and dragging the flicking should reproduce it.
Position is not reachable error occurs when using the `moveTo` method for the first panel with `bound: true`.
In the above demo, when 4 Panels are placed, the total number of Anchors is 2.
This is because the Panel labeled 1 and the Panel labeled 2 share the same Anchor point.
Similarly, the panel with 3 and the panel with 4 share the same anchor point.
This is because there is no way to send Panels 1 / 4 to the center with the bound option enabled, which removes the left and right empty spaces.
This means that in this situation, only the Anchor points of Panel 2 and Panel 3 exist.
If we use the `moveTo` method with Panel 1, the Anchor point we stop …
=> fix: add findActiveAnchor fallback for bound flicking

docs/docs/tutorials/installation.mdx, docs/docs/tutorials/polyfills.mdx, docs/docs/tutorials/quick-start.mdx
=> docs: fix polyfill mdx

src/Flicking.ts, test/unit/Flicking.spec.ts, test/unit/helper/test-util.ts, test/unit/setup.ts
=> fix: destroy after resize

docs/src/pages/Options.mdx, src/Flicking.ts, src/control/AxesController.ts, test/unit/Flicking.spec.ts
Sometimes we need to set the minimum pixel range to recognize the user's input.
We needed options for implementing cases where flicking doesn't move for very small movements.
To implement this now, we need to access `flicking.control._controller._panInput.options.threshold` directly like in the [demo](https://codepen.io/malangfox/pen/bGyKLRz).
Therefore, we added the `dragThreshold` option so that we can set an option for the PanInput instance in Flicking.
=> feat: add dragThreshold option

packages/vue3-flicking/src/Flicking.ts
Sometimes when mounting and unmounting different instances of Flicking slider, variable this.slotDiffer is undefined, throwing an exception on beforeUpdate() execution.
This fix is just to avoid the exception.
=> fix: Add check before update

docs/src/component/SourceCode.tsx, docs/src/component/code/AngularCode.tsx, docs/src/component/code/JavaScriptCode.tsx, docs/src/component/code/PreactCode.tsx, docs/src/component/code/ReactCode.tsx, docs/src/component/code/SvelteCode.tsx, docs/src/component/code/Vue3Code.tsx, docs/src/component/code/VueCode.tsx, docs/src/component/code/type.ts, docs/src/component/code/utils.ts, docs/src/css/demo/plugins.css, docs/src/demo/plugins/Arrow.tsx, docs/src/demo/plugins/Autoplay.tsx, docs/src/demo/plugins/Fade.tsx, docs/src/demo/plugins/Pagination.tsx, docs/src/demo/plugins/Parallax.tsx, docs/src/demo/plugins/Perspective.tsx, docs/src/pages/Plugins.mdx
This adds sample code with style to the Plugins section of the documentation.
After this PR is applied, the Plugins section will look like this: https://malangfox.github.io/egjs-flicking/Plugins
=> docs: add sample codes to plugins

packages/react-flicking/src/react-flicking/Flicking.tsx
https://github.com/naver/egjs-flicking/issues/905
Checks all props when determining whether the panel's state is updated.
=> fix: check other props for react state change

docs/docs/tutorials/quick-start.mdx
https://github.com/naver/egjs-flicking/issues/894
This solves the issue that new users of egjs-flicking may find if following the docs for quickstart located here https://naver.github.io/egjs-flicking/docs/quick-start
=> add preventDefaultOnDrag to quickstart's example

.github/workflows/run-test.yml, src/Flicking.ts, src/core/AutoResizer.ts, src/renderer/Renderer.ts, src/utils.ts, test/unit/Flicking.spec.ts, test/unit/renderer/Renderer.spec.ts
#883 
This fixes #883 by adding `resizeObservePanel` option to Flicking instance.
=> feat: add resizeObservePanel option
