naver/egjs-flicking

src/flicking.js
src/utils.js
test/unit/methods.spec.js

Implement method to get/set snapshot of current flicking contents
Ref #1

feat(flicking): Intent to ship new status methods

---

config/changelog.js
package.json

Running `npm run changelog` will generate changelog file based on commit logs.
Ref #11

chore(changelog): Auto generate changelog file

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

docs(github): Issue template

---

src/Flicking.js
src/eventHandler.js
test/unit/events.spec.js

#30
Changed setting animating property sequence value

fix(eventHandler): Adjust animation status

---

src/Flicking.js
test/unit/methods.spec.js

#19 
Add destroying axes & panInput instances

fix(Flicking): Fix destroying

---

package.json
src/Flicking.js
src/flicking.d.ts

#35 
- add type definition
- fix jsdoc document

chore(flicking.d.ts): add type definition

---

src/utils.js
test/unit/assets/fixture.js
test/unit/initialize.spec.js
test/unit/options.spec.js

#52
Added to sum padding value also

fix(utils): Correct getting panel's dimension

---

src/flicking.d.ts

#57
Declare return type for destroy and setStatus

style(d.ts): Add return types

---

.travis.yml
src/config.js
src/utils.js

#66
Remove unused & outdated code

style(utils): Remove outdated .isHWAccelerable()

---

config/uglify.js
package-lock.json
package.json
src/eventHandler.js
test/unit/events.spec.js
yarn.lock

#64
- Without an implicit user's action, the event's distance value should be set to null
- Update some dependency modules to the latest

fix(event): Set to null e.distance on API call

---

src/Flicking.js

#61
Mark param as deprecated, which will be removed in the next 4th release.

style(Flicking): Mark physical as deprecated

---

package-lock.json
package.json
src/Flicking.js
yarn.lock

#72, #73
Change import module from egjs-axes

chore(Flicking): Update egjs-axes to 2.4.2

---

.babelrc
package-lock.json
package.json
yarn.lock

#79
Update to babel-preset-es2015 to babel-preset-env

chore(module): Update babel-preset

---

src/Flicking.js
src/eventHandler.js
src/flicking.d.ts

#94
Get rid the ambiguity on importing all using *.

chore(all): Clarify modules imports

---

src/flicking.d.ts

chore(definition): Update getStatus return type

---

src/Flicking.js
src/config.js
src/utils.js
test/unit/options.spec.js

#113
- Implement useTranslate
- Change the panel's computation unit from integer to float

feat(options): Intent to ship useTranslate

---

src/Flicking.js
src/utils.js

#118
- Minimize the use of .getComputedStyle()
- Update hasClickBug() condition to target iOS only

refactor(style): Mitigate style recalculation

---

config/nightly.js
package.json
webpack.config.js

#119
Add nightly build command

chore(dev-env): Add nightly build

---

package.json
src/plugin/Plugin.js
src/plugin/effects/OpacityEffect.js
src/plugin/effects/ParallaxEffect.js

#122
- Correct work properly in different number of panels
- Fix incorrect interaction on non-circular mode
- Fix some typo and script command

fix(plugin): Fix parallaxEffect to work on multiple panels

---

src/Flicking.js
src/flicking.d.ts
test/unit/events.spec.js

fix(Flicking): fix prev/next method

---

packages/react-flicking/README.md

fix(react-infinitegrid): fix README

---

src/Flicking.js
test/unit/methods.spec.js

fix(Flicking): fix moveTo method for previewPadding and circular

---

src/plugin/Plugin.js

fix(plugin): fix distance for plugin

---

packages/react-flicking/README.md
packages/react-flicking/package.json
packages/react-flicking/src/react-flicking/index.tsx

fix(react-flicking): fix incorrect types

---

package-lock.json
package.json
src/eventHandler.js

fix(eventHandler): fix changeHandler for stop

---

package.json
src/Flicking.ts
src/components/Panel.ts
src/components/Viewport.ts
src/types.ts
test/manual/test.html
test/manual/test.js
test/unit/Panel.spec.ts
test/unit/methods.spec.ts

This fixes #177 
This also fixes #178 
This PR fixes both #177 , #178
Also it adds some missing tests.

fix: resizing in freescroll

---

demo/projects/shoppingsearch.html
src/components/PanelManager.ts
test/manual/test.js
test/unit/PanelManager.spec.ts

#181 
- This fixes #181 
- Add test for #181

fix: panels are empty after calling insertBefore or prepend

---

src/Flicking.ts
src/index.ts

fix: remove unsupported method

---

package-lock.json
src/components/Viewport.ts
test/manual/test.js
test/unit/methods.spec.ts

fix: current panel is null

---

src/Flicking.ts
src/components/Panel.ts
src/components/Viewport.ts
src/consts.ts
src/utils.ts
test/manual/test.html
test/manual/test.js
test/unit/assets/fixture.ts
test/unit/initialize.spec.ts

#198
- This resolves #198 
- It also can cope with `destroy()` calls.
- It includes some refactoring, and also adds some tests for new feature.

feat: make user to use existing Viewport and Camera element

---

src/Flicking.ts
src/components/Viewport.ts
src/types.ts
test/unit/initialize.spec.ts

feat: add update interface

---

src/Flicking.ts

#217
- This adds new method, `getLastIndex()`, to cope with external rendering.
- Did a few test complexity refactoring.

feat: add getLastIndex

---

package-lock.json
src/consts.ts
src/index.ts
src/types.ts
src/utils.ts
test/unit/initialize.spec.ts
tsconfig.test.json

feat: add withFlickingMethods decorator

---

src/utils.ts

fix: fix bug for node.js

---

package-lock.json
src/components/Viewport.ts
test/manual/html/resize.html
test/manual/js/resize.js

fix: correct resizing for height-dependent panel

---

src/components/Viewport.ts
test/unit/initialize.spec.ts

fix: every panel to be initialized with CSS "left"

---

src/components/Viewport.ts
test/unit/methods.spec.ts

#226, #227
This fixes #226
This resolves #227

feat: relative re-positioning in freeScroll

---

src/components/Panel.ts
src/components/Viewport.ts
src/moves/FreeScroll.ts
src/moves/MoveType.ts
src/moves/Snap.ts
src/states/DraggingState.ts
src/types.ts
src/utils.ts
test/manual/html/bound.html
test/manual/js/bound.js
test/unit/events.spec.ts

fix: change event is triggered on bound area

---

src/moves/FreeScroll.ts

fix: fix freeScroll's duration

---

src/Flicking.ts
src/components/Panel.ts
src/components/Viewport.ts
src/types.ts
test/manual/js/method.js
test/unit/methods.spec.ts

feat: add destroy()'s new option - "preserveUI"

---

demo/common/analytics.js
demo/common/codepen.js
demo/features/bound.html
demo/features/freescroll.html
demo/features/gap.html
demo/features/hangeranchor.html
demo/features/infiniteflicking.html
demo/features/progress.html
demo/features/snap.html
demo/features/variablesize.html
demo/plugins/autoplay.html
demo/plugins/fade.html
demo/plugins/parallax.html
demo/projects/artwindow.html
demo/projects/grafolio.html
demo/projects/keywords.html
demo/projects/mobileartwindow.html
demo/projects/post.html
demo/projects/shoppingsearch.html

demo: add google analytics

---

src/components/Viewport.ts
src/utils.ts
test/unit/initialize.spec.ts

#241, #243 
This fixes #241
It also fixes #243

fix: clone count calculation

---

src/Flicking.ts

fix: resize() binding for window resize event

---

packages/react-flicking/package-lock.json
packages/react-flicking/package.json
packages/react-flicking/src/react-flicking/Flicking.tsx

fix: enable renderExternal

---

src/components/Viewport.ts

fix: current panel can be cloned one

---

src/moves/Snap.ts
test/manual/html/bound.html
test/manual/js/bound.js
test/unit/initialize.spec.ts

fix: camera goes too far when bound is enabled

---

src/Flicking.ts
src/consts.ts
src/ga/ga.ts
src/types.ts
src/utils.ts
test/unit/assets/utils.ts
test/unit/initialize.spec.ts

feat: add useStatistics option for analytics

---

src/Flicking.ts
src/types.ts

fix: resize is regarded as member variable not method

---

README.md
README_KR.md
packages/ngx-flicking/README.md
packages/ngx-flicking/projects/ngx-flicking/README.md
packages/react-flicking/README.md
packages/vue-flicking/README.md

docs: collectStatistics on README

---

common/js/scene.js
index.html

fix: change to local dependency

---

package-lock.json
package.json
packages/react-flicking/package-lock.json
packages/react-flicking/src/react-flicking/Flicking.tsx
src/Flicking.ts
src/components/Panel.ts
src/components/Viewport.ts
src/consts.ts
src/types.ts
test/unit/Viewport.spec.ts
test/unit/methods.spec.ts

 feat: add beforeSync and mapVisiblePanels method

---

demo/features/infiniteflicking.html
packages/react-flicking/src/demo/css/infinite.css
packages/react-flicking/src/react-flicking/Flicking.tsx
packages/react-flicking/src/react-flicking/consts.ts
packages/react-flicking/src/react-flicking/types.ts
src/components/Viewport.ts

#273
As same with #282, this matches rendering method on React the same with native Flicking.

fix: rendering method for React

---

src/components/Viewport.ts
src/types.ts
test/manual/js/need.js
test/unit/events.spec.ts

feat: add fill() method for needPanel event

---

.editorconfig
karma.conf.js
test/hammer-simulator.run.js
test/setup.js
test/unit/assets/utils.ts
test/unit/events.spec.ts
test/unit/methods.spec.ts
test/unit/options.spec.ts

test: apply fake timer

---

src/consts.ts
src/utils.ts

utils and const depend on each other.
Ref #294

fix: circular dependency

---

packages/ngx-flicking/projects/ngx-flicking/package.json
packages/react-flicking/package.json
packages/vue-flicking/package.json

feat: update flicking 3.4 dependency

---

packages/ngx-flicking/projects/ngx-flicking/package-lock.json
packages/ngx-flicking/projects/ngx-flicking/src/lib/ngx-flicking.component.ts

fix: remove local dependency & private access

---

packages/ngx-flicking/projects/ngx-flicking/src/lib/ngx-flicking.component.ts
packages/react-flicking/src/react-flicking/Flicking.tsx
packages/vue-flicking/src/Flicking.ts
src/Flicking.ts
src/types.ts

fixes #301
I defined third parameter to collect information with GA.
This code is fine for framework users, but pure js user can pass useless things through third parameter. (This issue is already existed)
So before merge this PR, we need to think about how prevention that.

feat: collect information with GA

---

src/moves/Snap.ts
test/unit/events.spec.ts

fix: change event is triggered on bounce area

---

packages/ngx-flicking/projects/ngx-flicking/package.json
packages/react-flicking/package.json
packages/vue-flicking/package.json

It's just update dependencies for supported frameworks

update flicking dependencies

---

packages/ngx-flicking/projects/demo/src/app/app.module.ts
packages/ngx-flicking/projects/demo/src/app/infinite/infinite.component.ts
packages/ngx-flicking/projects/demo/src/app/panel/panel.component.html
packages/ngx-flicking/projects/demo/src/app/panel/panel.component.ts
packages/ngx-flicking/projects/demo/src/app/snap/snap.component.html
packages/ngx-flicking/projects/demo/src/app/snap/snap.component.ts
packages/ngx-flicking/projects/ngx-flicking/package-lock.json
packages/ngx-flicking/projects/ngx-flicking/package.json
packages/ngx-flicking/projects/ngx-flicking/src/lib/ngx-flicking.component.ts

fix: fix script error for OnPush mode

---

src/components/Viewport.ts
test/manual/css/common.css
test/manual/html/bound.html
test/manual/js/bound.js
test/unit/Viewport.spec.ts
test/unit/assets/fixture.ts

fix: scrollArea calculation when sum of the panel sizes is smaller than the viewport size

---

packages/vue-flicking/src/Flicking.ts
packages/vue-flicking/src/types.ts

fix: add missing typings of vue-flicking

---

src/consts.ts
src/types.ts
test/unit/options.spec.ts

fix: remove unnecessary method typings

---

packages/vue-flicking/demo/plugins/Autoplay.vue
packages/vue-flicking/demo/plugins/Fade.vue
packages/vue-flicking/demo/plugins/Parallax.vue
packages/vue-flicking/src/Flicking.ts

fix: text node can be used as panel

---

packages/ngx-flicking/projects/ngx-flicking/src/lib/FlickingInterface.ts
packages/ngx-flicking/projects/ngx-flicking/src/lib/ngx-flicking.component.ts
packages/ngx-flicking/projects/ngx-flicking/src/lib/types.ts

fix: fix angular's method types

---

src/Flicking.ts
src/components/Viewport.ts
test/manual/html/resize.html
test/manual/js/resize.js
test/unit/assets/fixture.css
test/unit/assets/fixture.ts
test/unit/methods.spec.ts

fix: prevent scrolling when resize

---

src/Flicking.ts
src/components/Panel.ts
src/components/Viewport.ts
src/states/AnimatingState.ts
test/manual/html/circular.html
test/manual/js/circular.js
test/manual/js/need.js
test/unit/events.spec.ts
test/unit/methods.spec.ts

fix: touchmove not triggered when renderOnlyVisible option is enabled

---

packages/react-flicking/package-lock.json
packages/react-flicking/package.json
packages/react-flicking/src/react-flicking/Flicking.tsx

fix: remove react-children-differ for strict

---

package-lock.json
package.json
src/Flicking.ts
src/components/Viewport.ts
src/consts.ts
src/types.ts
test/unit/options.spec.ts

feat: add iOSEdgeSwipeThreshold option #364

---

src/components/Viewport.ts
test/unit/assets/fixture.ts
test/unit/options.spec.ts

fix: renderOnlyVisible not correctly positioning panels on the first render

---

src/components/Viewport.ts
test/unit/options.spec.ts

#382 
This fixes an additional issue of #382

fix: apply panel offset for visible panels on resize

---

package-lock.json
src/Flicking.ts
test/unit/methods.spec.ts

fix: wrong rendering indexes after prepending panels

---

src/components/Viewport.ts
test/unit/methods.spec.ts

fix: next/prev/moveTo not work after calling disableInput while holding the panel

---

package-lock.json
src/components/Viewport.ts
test/unit/methods.spec.ts

fix: wrong camera position on setStatus

---

src/states/HoldingState.ts
src/types.ts
test/unit/events.spec.ts

feat: add element to select event

---

src/Flicking.ts
src/components/Viewport.ts
src/types.ts
test/unit/methods.spec.ts

fix: panel position is wrong after setStatus

---

packages/ngx-flicking/projects/ngx-flicking/src/lib/ngx-flicking.component.ts

fix: getCloneCount is not defined after destroy

---

package-lock.json
package.json
rollup.config.js
src/components/Viewport.ts
src/states/AnimatingState.ts
src/states/DisabledState.ts
src/states/DraggingState.ts
src/states/HoldingState.ts
src/states/IdleState.ts
src/states/State.ts
src/types.ts
test/manual/js/method.js

#432, #433 
This fixes #432, #433

fix: release immediately when the page's scrolling

---

package-lock.json
packages/react-flicking/src/demo/plugins/AutoPlay.tsx
src/Flicking.ts
src/components/Viewport.ts
test/unit/Viewport.spec.ts
test/unit/assets/fixture.ts
test/unit/methods.spec.ts
test/unit/options.spec.ts

fix: no current panel on the frameworks

---

packages/ngx-flicking/projects/ngx-flicking/src/public-api.ts
packages/react-flicking/src/react-flicking/index.ts
packages/vue-flicking/src/index.ts
packages/vue3-flicking/src/index.ts

fix: remove src exports

---

docs/docs/listening-to-events.mdx
docs/docusaurus.config.js
docs/package-lock.json
docs/package.json
docs/src/component/SourceCode.tsx
docs/src/demo/AddRemove.tsx
docs/src/demo/Grid.tsx
docs/src/demo/SideScroll.tsx
docs/src/demo/Sync.tsx
docs/src/demo/WeatherDisplay.tsx
docs/src/pages/Demos.mdx
docs/src/pages/Plugins.mdx
docs/src/pages/main/Frameworks.tsx
docs/src/pages/main/frameworks.module.css
package-lock.json

This adds source codes to the demos page.
> light
> dark

docs: add source code to demos

---

packages/ngx-flicking/projects/ngx-flicking/src/lib/ngx-flicking.component.ts
packages/react-flicking/src/react-flicking/Flicking.tsx

fix: events are missing methods in React

---

packages/ngx-flicking/projects/ngx-flicking/src/lib/consts.ts
packages/ngx-flicking/projects/ngx-flicking/src/lib/ngx-flicking.component.ts

fix: simplify event types

---

docs/src/component/code/AngularCode.tsx
docs/src/component/code/JavaScriptCode.tsx
docs/src/component/code/PreactCode.tsx
docs/src/component/code/ReactCode.tsx
docs/src/component/code/Vue3Code.tsx
docs/src/component/code/VueCode.tsx
docs/src/component/code/type.ts
docs/src/component/code/utils.ts
docs/src/demo/plugins/Arrow.tsx
docs/src/demo/plugins/Pagination.tsx
docs/src/pages/Plugins.mdx

This adds missing tutorials for Plugins CSS

docs: update plugins CSS import

---

docs/src/demo/AutoInit.tsx
src/Flicking.ts
src/control/AxesController.ts
test/manual/js/index.js
test/unit/Flicking.spec.ts

fix: preventClickOnDrag to work on non-native clickable elements

---

docs/src/component/EventFlicking.tsx
docs/src/pages/Options.mdx
src/Flicking.ts
src/control/Control.ts
test/manual/js/index.js
test/unit/Flicking.spec.ts

feat: add noEventsBeforeInit

---

src/control/AxesController.ts
test/unit/Flicking.spec.ts

fix: preventClickOnDrag prevents element on plugin elements

---

src/core/Viewport.ts
test/unit/core/Viewport.spec.ts

fix: viewport size calculation

---

src/Flicking.ts
src/camera/BoundCamera.ts
src/camera/Camera.ts
src/control/AxesController.ts
src/control/SnapControl.ts
src/control/StateMachine.ts
src/control/index.ts
src/control/states/AnimatingState.ts
src/control/states/IdleState.ts
src/control/states/State.ts
src/type/external.ts
src/utils.ts
test/manual/index.html
test/manual/js/index.js
test/unit/control/SnapControl.spec.ts

feat: add count option for snap control

---

src/cfc/sync.ts
test/unit/cfc/sync.spec.ts
test/unit/helper/El.ts

fix: cfc sync's removing algorithm

---

docs/src/component/code/AngularCode.tsx
docs/src/component/code/JavaScriptCode.tsx
docs/src/component/code/PreactCode.tsx
docs/src/component/code/ReactCode.tsx
docs/src/component/code/SvelteCode.tsx
docs/src/component/code/Vue3Code.tsx
docs/src/component/code/VueCode.tsx
docs/src/component/code/type.ts
docs/src/css/demo/date-selector.css
docs/src/demo/DateSelector.tsx
docs/src/pages/Demos.mdx

docs: add date selector demo

---

src/Flicking.ts

fix: panel is toggled while updating camera range

---

src/core/FlickingError.ts
src/utils.ts
test/manual/js/index.js

fix: setPrototypeOf is not defined on IE10 or lower

---

packages/vue3-flicking/package-lock.json
packages/vue3-flicking/package.json
packages/vue3-flicking/src/Flicking.ts

fix: vue3 render triggers update

---

src/Flicking.ts
src/camera/Camera.ts
src/camera/CircularCamera.ts
src/control/AxesController.ts
src/control/Control.ts
src/control/FreeControl.ts
src/control/StrictControl.ts
src/control/states/AnimatingState.ts
src/control/states/State.ts
src/renderer/Renderer.ts
test/unit/Flicking.spec.ts
test/unit/camera/Camera.spec.ts
test/unit/camera/CircularCamera.spec.ts
test/unit/control/AxesController.spec.ts
test/unit/control/Control.spec.ts

fix: Flicking is animating on moveEnd event

---

docs/.eslintrc.js
docs/package-lock.json
docs/package.json
docs/src/css/demo/lazyload.module.css
docs/src/demo/LazyLoad.tsx
docs/src/demo/code/LazyLoad/angular.tsx
docs/src/demo/code/LazyLoad/js.tsx
docs/src/demo/code/LazyLoad/react.tsx
docs/src/demo/code/LazyLoad/svelte.tsx
docs/src/demo/code/LazyLoad/vue.tsx
docs/src/pages/Demos.mdx

docs: add lazyload panels demo

---

src/cfc/getRenderingPanels.ts
test/unit/cfc/getRenderingPanels.spec.ts

fix: getRenderingPanels uses old list

---

docs/package-lock.json
docs/package.json
docs/src/demo/WeatherDisplay.tsx
docs/src/pages/Options.mdx
docs/src/pages/main/MainLogo.tsx
package-lock.json
package.json
src/Flicking.ts
src/control/AxesController.ts
src/control/Control.ts
src/core/panel/Panel.ts
src/renderer/Renderer.ts
test/manual/css/index.css
test/manual/index.html
test/manual/js/index.js
test/unit/Flicking.spec.ts
test/unit/core/Panel.spec.ts
test/unit/helper/El.ts
test/unit/helper/test-util.ts
test/unit/renderer/Renderer.spec.ts
test/unit/setup.js

#546 
This resolves #546 
This fixes #548

feat: add resizeOnContentsReady

---

packages/ngx-flicking/projects/ngx-flicking/src/lib/ngx-flicking.component.ts

fix: window is not defined on angular universal

---

packages/ngx-flicking/projects/ngx-flicking/src/lib/ngx-flicking.component.ts

fix: HostBinding should be static

---

packages/react-flicking/src/demo/App.tsx
packages/react-flicking/src/react-flicking/Flicking.tsx
packages/react-flicking/src/react-flicking/ViewportSlot.tsx

fix: Flicking throws error on react strict mode

---

packages/vue3-flicking/demo/App.vue
packages/vue3-flicking/package-lock.json
packages/vue3-flicking/package.json
packages/vue3-flicking/src/VueElementProvider.ts
packages/vue3-flicking/src/VuePanel.ts
packages/vue3-flicking/tsconfig.json

fix: vue3-flicking can't refresh panel element

---

packages/vue3-flicking/src/FlickingProps.ts

fix: typing error due to the default value

---

docs/docs/quick-start.mdx
docs/versioned_docs/version-4.0.0/quick-start.mdx
docs/versioned_docs/version-4.1.1/quick-start.mdx
docs/versioned_docs/version-4.2.5/quick-start.mdx
docs/versioned_docs/version-4.3.1/quick-start.mdx
docs/versioned_docs/version-4.4.0/quick-start.mdx
packages/ngx-flicking/projects/ngx-flicking/README.md

This fixes some old documents that has a deprecated option

docs: remove deprecated options

---

.gitignore
package-lock.json
package.json
rollup.config.development.js
src/components/Viewport.ts
test/manual/html/bound.html
test/manual/html/circular.html
test/manual/html/default.html
test/manual/html/method.html
test/manual/html/moves.html
test/manual/html/need.html
test/manual/html/perf.html
test/manual/html/resize.html
test/manual/html/stop.html
test/manual/html/vertical.html
test/unit/events.spec.ts

fix: direction is always null after disabling input

---

package-lock.json
package.json
src/Flicking.ts
src/components/AutoResizer.ts
src/consts.ts
src/types.ts
test/unit/options.spec.ts
tsconfig.test.json

This adds a new option: `useResizeObserver`

feat: add useResizeObserver

---

.github/workflows/run-test.yml
src/camera/Camera.ts
src/cfc/sync.ts
test/cfc/framework/preact/jest.config.js
test/cfc/replace-coverage.js
test/manual/index.html
test/unit/cfc/sync.spec.ts

fix: wrong sync behavior when removing all prev panels

---

package-lock.json
package.json
packages/ngx-flicking/package-lock.json
packages/ngx-flicking/projects/ngx-flicking/package-lock.json
packages/ngx-flicking/projects/ngx-flicking/package.json
packages/ngx-flicking/projects/ngx-flicking/src/lib/ngx-flicking-panel.directive.ts
packages/ngx-flicking/projects/ngx-flicking/src/lib/ngx-flicking.component.ts
test/cfc/common/global-setup.ts

Looks like style import is removed by mistake, this PR revokes that.

fix: missing style url in Angular

---

src/components/Viewport.ts

fix: wrong non-null assertion on panel cloning

---

packages/vue-flicking/src/VueElementProvider.ts
packages/vue-flicking/src/VuePanel.ts
test/cfc/common/global-teardown.ts
test/cfc/framework/preact/babel.js
test/cfc/suite/render.spec.ts

fix: vue-flicking panels are targeting old element

---

docs/package-lock.json
docs/package.json
docs/src/css/demo/plugins.css
docs/src/demo/code/LazyLoad/angular.tsx
docs/src/demo/code/LazyLoad/js.tsx
docs/src/demo/code/LazyLoad/react.tsx
docs/src/demo/code/LazyLoad/svelte.tsx
docs/src/demo/code/LazyLoad/vue.tsx
docs/src/demo/plugins/Perspective.tsx
docs/src/demo/plugins/Sync-code/camera/angular.tsx
docs/src/demo/plugins/Sync-code/camera/js.tsx
docs/src/demo/plugins/Sync-code/camera/react.tsx
docs/src/demo/plugins/Sync-code/camera/svelte.tsx
docs/src/demo/plugins/Sync-code/camera/vue.tsx
docs/src/demo/plugins/Sync-code/index/angular.tsx
docs/src/demo/plugins/Sync-code/index/js.tsx
docs/src/demo/plugins/Sync-code/index/react.tsx
docs/src/demo/plugins/Sync-code/index/svelte.tsx
docs/src/demo/plugins/Sync-code/index/vue.tsx
docs/src/pages/Options.mdx
docs/src/pages/Plugins.mdx

This adds demo for the new plugin `Perspective`

docs: add perspective demo

---

src/control/StrictControl.ts
test/manual/css/index.css
test/manual/index.html
test/manual/js/index.js
test/unit/Flicking.spec.ts
test/unit/karma.conf.js
test/unit/package-lock.json

fix: strict control can't move to far index

---

docs/src/pages/Main.tsx

docs: wrong link at main page

---

src/components/PanelManager.ts
test/unit/Viewport.spec.ts

fix: removed panel should not included as visible panel

---

src/cfc/withFlickingMethods.ts

fix: change startsWith method

---

packages/vue3-flicking/src/Flicking.ts

fix: v-if rendering on Vue3

---

src/control/Control.ts
src/control/FreeControl.ts
src/control/SnapControl.ts
src/control/StrictControl.ts
src/control/states/AnimatingState.ts
src/control/states/DraggingState.ts
test/manual/index.html
test/manual/js/index.js
test/unit/Flicking.spec.ts
test/unit/control/FreeControl.spec.ts
test/unit/control/SnapControl.spec.ts
test/unit/control/StrictControl.spec.ts

This fix ensures `willChange` and `willRestore` can be stopped.

fix: stop willChange event

---

packages/react-flicking/rollup.config.js
src/renderer/Renderer.ts

This adds umd build for React env
```js
typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory(require('react'), require('@egjs/component'), require('@egjs/list-differ'), require('@egjs/flicking'), require('react-dom')) :
typeof define === 'function' && define.amd ? define(['react', '@egjs/component', '@egjs/list-differ', '@egjs/flicking', 'react-dom'], factory) :
(global = typeof globalThis !== 'undefined' ? globalThis : global || self, global.ReactFlicking = factory(global.React, global.Component, global.eg.ListDiffer, global.Flicking, global.ReactDOM));
```

feat: add umd distribution for React

---

docs/docusaurus.config.js
docs/package-lock.json
package-lock.json
src/Flicking.ts
test/manual/css/index.css
test/manual/js/index.js
test/unit/Flicking.spec.ts

- This fixes Flicking having the wrong camera offset after calling `resize()` in some cases.
- This also fixes Flicking doesn't update height after `resize` when `adaptive: true`

fix: wrong camera offset on adaptive resize

---

docs/src/pages/Options.mdx
src/Flicking.ts
src/control/SnapControl.ts
src/control/StrictControl.ts
src/control/states/AnimatingState.ts
test/manual/js/index.js
test/unit/Flicking.spec.ts

This adds a new option "changeOnHold", which triggers `changed` event on mouse/touch hold while animating.

feat: add changeOnHold

---

src/control/SnapControl.ts
test/manual/js/index.js
test/unit/control/SnapControl.spec.ts

fix: spinning on moving to adjacent panel & restoring

---

docs/src/pages/Options.mdx
src/Flicking.ts
src/core/Viewport.ts
src/core/panel/Panel.ts
src/utils.ts
test/unit/core/Viewport.spec.ts
test/unit/utils.spec.ts

This adds a new option - useFractionalSize

feat: add useFractionalSize

---

packages/react-flicking/src/react-flicking/Flicking.tsx

#719 
This fixes the bug in react-flicking that the updated panels are not applied when the list of panels are updated in hooks.

fix: fix panels could not be updated inside hooks

---

packages/react-flicking/src/react-flicking/Flicking.tsx

#736 
This fixes #736 
Tested this doesn't produce any error furthermore on both this two test cases:
- https://github.com/neizzz/flicking-bug-reproduction
- https://codesandbox.io/s/flicking-change-data-bug-voblvn

fix: react - prevent update between rendering

---

docs/package-lock.json
docs/package.json
docs/src/pages/Plugins.mdx

This adds documentation for `renderActiveBullet` option of the `Pagination` plugin.

docs: add renderActiveBullet docs

---

package.json
rollup.config.js
src/index.cjs.ts

fix: add cjs file

---

docs/src/demo/plugins/Arrow.tsx

#822 
This fixes the demo of the Arrow plugin in the docs.

fix: fix Arrow demo in docs

---

src/utils.ts
test/unit/Flicking.spec.ts

fix: fix size NaN

---

package.json

This fixes https://github.com/naver/egjs-axes/issues/221 by updating @egjs/axes to 3.9.2

chore: update @egjs/axes to 3.9.2
